### PR TITLE
Feature/solidity 0.5

### PR DESCRIPTION
**Pull request by H34D**
## Description

Migrated to solidity `0.5.3`

## Is this PR related with an open issue?

Related to Issue #181 #287

### CODE REVIEW

**Comment by aaitor** [comment]
@H34D , did you check if web3 implementations we have (js, py, java) are compatible with solidity 0.5?
Without that confirmation, I wouldn't upgrade the solidity version.

**Comment by H34D** [comment]
> @H34D , did you check if web3 implementations we have (js, py, java) are compatible with solidity 0.5?
> Without that confirmation, I wouldn't upgrade the solidity version.

unit tests are using web3, i validated this

**Comment by H34D** [comment]
> I think this need to be confirmed in the 3 web3 frameworks we are using. Hopefully the change doesn't affect those frameworks, but could happen that one of them doesn't support solidity 0.5 yet. It would compromise the release of one of the squid implementations for v1.
> 
> @josepablofm78 , please can you check if web3j v4.x supports solidity 0.5.x?
> @ssallam , please can you check if the version of web3-py we are using supports solidity 0.5.x? If not should we migrate to web3-py 5.x?
> @Pedro-vk , please can you check if the version we are using now of web3-js in squid-js is compatible with solidity 0.5.x?

no web3 is using the EVM not the bytecode directly, i triple checked the ABI's did not change (unless to the changes that we did). It should totally transparent for the consumer. Also the deployment behaves normal.

**Comment by Pedro-vk** [comment]
> > unit tests are using web3, i validated this
> 
> I think this need to be confirmed in the 3 web3 frameworks we are using. Hopefully the change doesn't affect those frameworks, but could happen that one of them doesn't support solidity 0.5 yet. It would compromise the release of one of the squid implementations for v1.
> 
> @josepablofm78 , please can you check if web3j v4.x supports solidity 0.5.x?
> @ssallam , please can you check if the version of web3-py we are using supports solidity 0.5.x? If not should we migrate to web3-py 5.x?
> @Pedro-vk , please can you check if the version we are using now of web3-js in squid-js is compatible with solidity 0.5.x?

As @H34D said, it doesn't depend on Web3. Only affects if has been changed any contract.
@aaitor from my point of view, it should be ok. Do you think that we should do extra tests? Like trying to use this version before merge it? (deploying a temporal artefact)

**Comment by aaitor** [comment]
@Pedro-vk , I'm not concerned about web3-js because @H34D tested in the keeper using the tests.
But taking into account previous parties with different web3 implementations, I would double check.

**Comment by H34D** [comment]
i will move this to 0.7

**Comment by aaitor** [comment]
agree

**Comment by aaitor** [comment]
> i will move this to 0.7

agree

**Comment by H34D** [comment]
merged to `release/v0.7`

**Pull request closed without merging**
