### PR TITLE
restructure directories and contracts naming convention

### PR DESCRIPTION
**Pull request by aabdulwahed**
## Description
If you agree on this restructure, and the naming convention we can work on this else, we can keep it as it is, but from my side I prefer make it now to avoid ambiguity of code and style.  

Restructure keeper contracts into key components:

- Conditions
- Service Agreement
- Token
- Registry

And following the same naming convention for the contracts and directories:
- Folders (small characters)
- Contract Naming: short and camel case naming convention.
 
## Is this PR related with an open issue?

Related to Issue #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [x] Follows the code style of this project.
- [x] Tests Cover Changes
- [ ] Documentation

### CODE REVIEW

**Comment by H34D** [comment]
This has a lot of implications:

* all the tests would need to be reworked
* all the contracts would need to be reworked
* all migration scripts would need to be reworked
* all artifacts would be renamed
* all squid implementations (py,js,java) would need to be adapted

I would recommend doing this after trilobite.

**Comment by aabdulwahed** [comment]
- [ ] contracts compilation passed
- [ ] migration scripts works
- [ ] Test cases works
- [ ] Artifacts naming fixed
- [ ] Squid (js/py/java)

**Comment by ldmberman** [comment]
`Market` and `Jwt` are not condition contracts so you might want to keep them outside of the `conditions folder`.

Also, I see there are still some mentions (variable names, comments, etc) of `OceanAuth` and `OceanToken` - just grep them.

**Comment by aabdulwahed** [comment]
@ldmberman  `Jwt` contract will be refactored to provide the jwt token based on-chain access control as a condition. For optionality, you can use `jwt` or `secret store`. Regarding `market` I think this will be merged with `Payments` and have one contract including the same interfaces but without duplicates.

- Regarding the variable names, I'm working on fixing them.

**Pull request closed without merging**
